Separate github jobs

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,7 +7,7 @@ on:
     branches: [main]
 
 jobs:
-  test:
+  test-matrix:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -33,3 +33,16 @@ jobs:
     - name: Run tests
       run: |
         pytest --maxfail=1 --disable-warnings --exitfirst
+
+  test:
+    runs-on: ubuntu-latest
+    needs: test-matrix
+    if: always()
+    steps:
+    - name: Check test matrix results
+      run: |
+        if [[ "${{ needs.test-matrix.result }}" != "success" ]]; then
+          echo "Tests failed"
+          exit 1
+        fi
+        echo "All tests passed"
